### PR TITLE
Use keyof object in Omit for better type checking

### PR DESCRIPTION
**Pull request by vlazh**

### CODE REVIEW

**Comment by gcanti** [comment]
@vlazh could you please explain what's the benefit? Now I can do

```ts
type A = { a: number; c: string }
type B = { a: boolean; b: string }
type C = Omit<B, keyof A>
```

with this change I must do

```ts
type A = { a: number; c: string }
type B = { a: boolean; b: string }
type C = Omit<B, keyof A & keyof B>
```

> for better type checking

what's the use case which led to this change?

**Comment by vlazh** [comment]
```ts
type A = { aa: number; cc: string }
type B = Omit<A, 'a'> // compiler can't check that `a` don't belong to `A`. I have issue just with this case
```

```ts
type A = { a: number; c: string }
type B = { a: boolean; b: string }
type C = Omit<B, keyof A>
```
It feels like an exclusion. What if `A` doesn't contain `a` and any other intersections? In this case `Omit` is totally not needed and compiler can't tell about it.
May be need other type like OmitKeys or ExcludeKeys?
```ts
type ExcludeKeys<A extends object, K extends string | number | symbol> = Pick<A, Exclude<keyof A, K>>;
type C = ExcludeKeys<B, keyof A>
```
Or may be extend `Omit`?
```ts
type Omit<
  A extends object,
  K extends undefined extends D ? keyof A : object,
  D extends keyof K = any
> = Pick<A, Exclude<keyof A, K extends keyof A ? K : D>>;
type C = Omit<B, A, keyof A>;
// or
type C = Omit<B, 'a'>;
```

**Comment by vlazh** [comment]
And one more strictly:
```ts
type Omit<
  A extends object,
  K extends undefined extends D
    ? keyof A
    : (Extract<keyof A, D> extends never ? never : Pick<K, Extract<keyof A, D>>),
  D extends keyof K = any
> = Pick<A, Exclude<keyof A, K extends keyof A ? K : D>>;

type A = { a: number; c: string }
type B = { a: boolean; b: string }
type D = { d: number; e: string }

type C = Omit<B, 'a'>; // OK. Exclude `a` from `B`
type C = Omit<B, A, keyof A>; // OK. Exclude all intersections with `A`
// but
type C = Omit<B, A, 'c'>; // Error: `c` not containt in `B`
type C = Omit<B, D, keyof D>; // Error: `D` has no any intersections with `B`, so `Omit` is unnecessary.  
```

**Comment by vlazh** [comment]
I found simpler solution but without autocomplete support:
```ts
type Omit<
  A extends object,
  K extends Extract<keyof A, K> extends never ? never : PropertyKey
> = Pick<A, Exclude<keyof A, K>>;

type A = { a: number; c: string }
type B = { a: boolean; b: string }
type D = { d: number; e: string }

type C = Omit<B, 'a'>; // OK. Exclude `a` from `B`
type C = Omit<B, keyof A>; // OK. Exclude all intersections with `A`
// but
type C = Omit<B, 'c'>; // Error: `c` not containt in `B`
type C = Omit<B, keyof D>; // Error: `D` has no any intersections with `B`, so `Omit` is unnecessary.  
```

**Comment by raveclassic** [comment]
@vlazh Looks interesting but still could you please describe the use case? It looks ok to me that if you're trying to exclude a non-existent key from an object then you get the same object without any errors, don't you think?

**Comment by raveclassic** [comment]
So I guess it's more about developer experience/polishing the code than fixing some type-related issues, right?
Anyway, I don't have any strong opinion about this issue so it's up to @gcanti to decide, just wanted to ask.

**Comment by vlazh** [comment]
I think it is type-related issue. Typescript is for type checking, right? Why not use this power? Diff uses known keys and it's not bad.

**Comment by raveclassic** [comment]
I agree, I just mean that it's more an improvement than a fix. Moreover it's a breaking change according to @gcanti comment. That's why I asked for the use case.

**Comment by vlazh** [comment]
Yeah, it might be problems for many code bases. So perhaps I should use the [general implementation](https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-307871458).

**Comment by vlazh** [comment]
It is all I have been able to think for less pain of using suggested `Omit` implementation in existing codebase. Fortunately compiler will be able to show an mistakes. Autocomplete of keys also supports.
 
```ts
type Omit<
  A extends object,
  K extends Extract<K, K> extends keyof A
    ? keyof A
    : (Extract<keyof A, keyof K> extends never ? never : Pick<K, Extract<keyof A, keyof K>>)
> = Pick<A, Exclude<keyof A, K extends keyof A ? K : keyof K>>;

type A = { a: number; c: string }
type B = { a: boolean; b: string }
type D = { d: number; e: string }

type C = Omit<B, 'a'>; // OK
type C = Omit<B, 'a' | 'c'>; // Error: `c` not in `B`
type C = Omit<B, keyof A>; // Error
type C = Omit<B, A>; // OK: Exclude all intersections with A
type C = Omit<B, D>; // Error: `D` has no any intersections with `B`, so `Omit` is unnecessary.  
```

**Comment by vlazh** [comment]
PR is no longer relevant.

**Pull request closed without merging**
